https://www.tutorialspoint.com/numpy/index.htm

In [1]:
import numpy as np

# ndarray

In [2]:
a = np.array((1,2,3))
a

array([1, 2, 3])

In [3]:
a = np.array(((1,2,3),(4,5,6)))
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.array((1,2,3), ndmin=2)

array([[1, 2, 3]])

In [5]:
np.array((1,2,3), dtype=float)

array([1., 2., 3.])

### dtype

In [6]:
dt = np.dtype([('age', np.int8)])
a = np.array([(10,),(20,),(20,)], dtype=dt)
print(a['age'])

[10 20 20]


In [7]:
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print(a)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


### shape

In [8]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a.shape

(2, 3)

In [10]:
a.shape = (3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

### sundry

In [11]:
a.ndim

2

In [12]:
a.itemsize

8

In [13]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

### init

In [14]:
np.empty((2,3))

array([[4.66229091e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [15]:
np.empty((2,3), dtype=int)

array([[94365818578688,              0,              0],
       [             0,              0,              0]])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [18]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [19]:
np.arange(1, 10, 3)  # start, stop, step

array([1, 4, 7])

In [20]:
np.linspace(1, 10, 3)  # start, stop, count

array([ 1. ,  5.5, 10. ])

In [21]:
np.linspace(1, 10, 3, dtype=int)

array([ 1,  5, 10])

np.logspace(1, 2)

### indexing and slicing

In [22]:
np.arange(10)[5]

5

In [23]:
np.arange(10)[2:5]  # start:stop

array([2, 3, 4])

In [24]:
np.arange(10)[2:7:2]  # start:stop:step

array([2, 4, 6])

In [25]:
a = np.array(((1,2,3),(4,5,6),(7,8,9)))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
# starting at first row
a[1:]

array([[4, 5, 6],
       [7, 8, 9]])

### integer index

In [27]:
a[(0,2),]  # specific index by row

array([[1, 2, 3],
       [7, 8, 9]])

In [28]:
# first and last row, third column
a[(0,-1),(2,)]

array([3, 9])

In [29]:
# four corners (slice of slice)
a[(0,-1),][...,(0,-1)]

array([[1, 3],
       [7, 9]])

### boolean index

In [30]:
a > 3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [31]:
a[a > 3]

array([4, 5, 6, 7, 8, 9])

### broadcast

In [49]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])
print(a)
print()
print(b)

[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]

[1. 2. 3.]


In [46]:
a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

### iteration