https://www.tutorialspoint.com/numpy/index.htm

In [1]:
import numpy as np

# ndarray

In [4]:
a = np.array((1,2,3))
a

array([1, 2, 3])

In [31]:
a = np.array(((1,2,3),(4,5,6)))
a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.array((1,2,3), ndmin=2)

array([[1, 2, 3]])

In [11]:
np.array((1,2,3), dtype=float)

array([1., 2., 3.])

### dtype

In [23]:
dt = np.dtype([('age', np.int8)])
a = np.array([(10,),(20,),(20,)], dtype=dt)
print(a['age'])

[10 20 20]


In [26]:
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print(a)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]
