https://www.tutorialspoint.com/numpy/index.htm

In [3]:
import numpy as np

# ndarray

In [4]:
a = np.array((1,2,3))
a

array([1, 2, 3])

In [31]:
a = np.array(((1,2,3),(4,5,6)))
a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.array((1,2,3), ndmin=2)

array([[1, 2, 3]])

In [11]:
np.array((1,2,3), dtype=float)

array([1., 2., 3.])

### dtype

In [23]:
dt = np.dtype([('age', np.int8)])
a = np.array([(10,),(20,),(20,)], dtype=dt)
print(a['age'])

[10 20 20]


In [26]:
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print(a)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


### shape

In [9]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a.shape

(2, 3)

In [8]:
a.shape = (3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

### sundry

In [14]:
a.ndim

2

In [15]:
a.itemsize

8

In [17]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

### init

In [20]:
np.empty((2,3))

array([[4.64121726e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [22]:
np.empty((2,3), dtype=int)

array([[93939281407824,              0,              0],
       [             0,              0,              0]])

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [27]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [34]:
np.arange(1, 10, 3)  # start, stop, step

array([1, 4, 7])

In [36]:
np.linspace(1, 10, 3)  # start, stop, count

array([ 1,  5, 10])

In [37]:
np.linspace(1, 10, 3, dtype=int)

array([ 1,  5, 10])

np.logspace(1, 2)

### indexing and slicing

In [57]:
np.arange(10)[5]

5

In [60]:
np.arange(10)[2:5]  # start:stop

array([2, 3, 4])

In [61]:
np.arange(10)[2:7:2]  # start:stop:step

array([2, 4, 6])

In [66]:
a = np.array(((1,2,3),(4,5,6),(7,8,9)))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
# starting at first row
a[1:]

array([[4, 5, 6],
       [7, 8, 9]])

### integer index

In [95]:
a[(0,2),]  # specific index by row

array([[1, 2, 3],
       [7, 8, 9]])

In [100]:
# first and last row, third column
a[(0,-1),(2,)]

array([3, 9])

In [109]:
# four corners (slice of slice)
a[(0,-1),][...,(0,-1)]

array([[1, 3],
       [7, 9]])